schemaVersion: "2.0.0"

# A basic example to verify the cassandra docker image.
# This shouldn't be needed at all, but is a nice backup
# check since the pull doesn't support digest mode.

fileExistenceTests:
  - name: 'cassandra jar exists'
    path: '/usr/share/cassandra/apache-cassandra-3.11.1.jar'
    shouldExist: true
    permissions: '-rw-r--r--'

commandTests:
  - name: "cassandra jar validation"
    command: "md5sum"
    args: ["/usr/share/cassandra/apache-cassandra-3.11.1.jar"]
    expectedOutput: ["40d689fd3c8af1715eb5efcd54b72019  /usr/share/cassandra/apache-cassandra-3.11.1.jar\n"]

metadataTest:
  env:
    - key: "CASSANDRA_VERSION"
      value: "3.11.1"
  exposedPorts: ["7000", "7001", "7199", "9042", "9160"]
  volumes: ["/var/lib/cassandra"]
  entrypoint: ["docker-entrypoint.sh"]
  cmd: ["cassandra", "-f"]
  workdir: ["/"]